# Generated by Django 5.2.5 on 2025-09-04 20:01

import primera_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_biblioteca_lector_libro_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamo',
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='comuna',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='direccion',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='lector',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='libro',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='created_at',
            field=models.DateField(default=primera_app.models.ahora),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
