# Generated by Django 5.2.5 on 2025-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0003_remove_prestamo_fecha_prestamo_autor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
