# Generated by Django 4.2.25 on 2025-10-29 20:19

from django.db import migrations, models
import primera_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0005_alter_autor_created_at_alter_autor_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[primera_app.models.validar_rut]),
        ),
    ]
