# Generated by Django 4.2.25 on 2025-10-29 20:37

from django.db import migrations, models
import django.db.models.deletion
import primera_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0006_remove_lector_digito_verificador_alter_lector_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='direccion',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(null=True, validators=[primera_app.models.validar_mayoria_edad]),
        ),
        migrations.AddField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.nacionalidad'),
        ),
    ]
